bosch:
  log_file: storage/sensors-bosch.log
  burn_time: 5
  heater_temp: 320
  heater_duration: 150
  heater_profile: 0
  
enviro:
  log_file: storage/sensors-enviro.log
  precision: 4

main: 
  interval: 30
  log_file: storage/sensors.log
  pid: storage/sensors.pid
  
tracker:
  log_file: storage/sensors-tracker.log
  endpoint: "https://sensors.progress44.com/v1/environment"
